name: Deploy to S3

on:
  push:
    branches:
      - master

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          path: portfolio # Specify the directory where the repository should be checked out

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Check npm version
        run: npm --version

      - name: Install dependencies
        run: |
          cd portfolio
          npm install --verbose

      - name: Build project
        run: |
          cd portfolio
          npm run build

      - name: Deploy to S3
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: ${{ secrets.AWS_REGION }}
          S3_BUCKET_NAME: ${{ secrets.S3_BUCKET_NAME }}
        run: |
          npm install -g aws-cli
          aws s3 sync portfolio/build/ s3://$S3_BUCKET_NAME --delete
